# Config format schema number
format_version: 2


###################
## Model options
model_params:
  model_architecture: "spvcnn"

  input_dims: 4
  voxel_size: 0.05
  cr: 1  # enlarge factor of layer_num
  layer_num:
    - 32
    - 32
    - 64
    - 128
    - 256
    - 256
    - 128
    - 96
    - 96

  num_class: 24


###################
## Dataset options
dataset_params:
  training_size: 19132
  dataset_type: "voxel_dataset"
  pc_dataset_type: "MCDNTU"
  collate_type: "collate_fn_voxel"
  ignore_label: 255
  label_mapping: "./config/label_mapping/mcd-ntu.yaml"

  seg_labelweights:
    - 1844088
    - 49941
    - 9284949
    - 16777
    - 24992
    - 14487
    - 916817
    - 234149
    - 5064
    - 477793
    - 874598
    - 15919
    - 332691
    - 56787
    - 504669
    - 13169312
    - 655522
    - 2466956
    - 136540
    - 13271
    - 26812
    - 589043
    - 19739499
    - 948948

  train_data_loader:
    data_path: "./dataset/MCD_NTU/"
    batch_size: 8
    shuffle: True
    num_workers: 8
    rotate_aug: True
    flip_aug: True
    scale_aug: True
    transform_aug: True
    dropout_aug: True

  val_data_loader:
    data_path: "./dataset/MCD_NTU/"
    shuffle: False
    num_workers: 8
    batch_size: 8
    rotate_aug: False
    flip_aug: False
    scale_aug: False
    transform_aug: False
    dropout_aug: False


###################
## Train params
train_params:
  max_num_epochs: 64
  learning_rate: 2.4e-1
  optimizer: SGD  # [SGD, Adam]
  lr_scheduler: CosineAnnealingWarmRestarts  # [StepLR, ReduceLROnPlateau, CosineAnnealingLR, CosineAnnealingWarmRestarts]
  momentum: 0.9
  nesterov: True
  weight_decay: 1.0e-4